version: "3.8"
services:
  recycle-ai:
    build: .
    image: recycle-ai:latest
    container_name: recycle-ai
    networks:
      - codeforchange_network
    env_file:
      - .env
networks:
  codeforchange_network:
    external: true
